[Nvim] Remove nvim-spectre
Due to:
error: hash mismatch in fixed-output derivation '/nix/store/jpjvdsmyw6dwqaf35v8b07x3rp0gdf42-spectre_oxi-2024-06-25-vendor.tar.gz.drv':
         specified: sha256-ZBlxJjkHb2buvXK6VGP6FMnSFk8RUX7IgHjNofnGDAs=
            got:    sha256-SqbU9YwZ5pvdFUr7XBAkkfoqiLHI0JwJRwH7Wj1JDNg=